# Site settings
title: Andrea Margiovanni
email: hello@margiovanni.it
description: >-
  Head of Technology Solutions @ Oltrematica.
  Turning ideas into digital products that make a difference.
baseurl: ""
url: "https://margiovanni.it"

# Author information
author:
  name: Andrea Margiovanni
  email: hello@margiovanni.it
  linkedin: https://www.linkedin.com/in/margio/
  bluesky: https://bsky.app/profile/margio.uk

# Build settings
markdown: kramdown
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: false
permalink: /blog/:year/:month/:day/:title/

# Collections
collections:
  posts:
    output: true
    permalink: /blog/:year/:month/:day/:title/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

# Include in processing
include:
  - _headers
  - robots.txt

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .DS_Store
  - README.md

# Pagination
paginate: 5
paginate_path: "/blog/page/:num/"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap
  - liquid_reading_time
